spring:
  application:
    name: spring-ai-mcp-mysql-chat
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-mysql-chat-client
        request-timeout: 30s
        type: SYNC
        version: 1.0.0
        stdio:
#          connections:
#            server:
#              command: java
#              args:
#                - -jar
#                - mysql/mcp-mysql-server/target/mcp-mysql-server-1.0.0-SNAPSHOT.jar
#              env:
#                - MYSQL_USER:root
#                - MYSQL_PASSWORD:Admin123
#                - MYSQL_DATABASE:mcp
          servers-configuration: classpath:mcp-servers-config.json
    openai:
      api-key: sk-05eedd2cbb9a4b21ae6fe6bc08ac2fe1
      base-url: https://dashscope.aliyuncs.com
      chat:
        enabled: on
        options:
          model: qwen-plus
        completions-path: /compatible-mode/v1/chat/completions

